### ISSUE TITLE
why do you use GCP Pubsub

### ISSUE THREAD

**Issue by MaryLilian** [iamolegga/nestjs-gcp-pubsub#165]
Hi, I am reading your project and I love this project
I have a question, why do you choose GCP Pubsub in your project instead of others like RabbitMQ or Kafka, are there any special features that others dont have it. Can you share me it. I am wondering when I should choose GCP Pubsub instead of others like RabbitMQ or Kafka

**Comment by iamolegga** [comment]
Hi, I think it's better to use official docs to decide which works better for your case: https://cloud.google.com/pubsub
